### ISSUE TITLE
Database not persistent across deployes/restarts

### ISSUE THREAD

**Issue by mmk2410** [eXodiquas/surlicious#4]
Since the Docker Compose setup does not configure a volume for storing the database, it is deleted after every deploy/restart.

### Problem

The frequent need to complete setup the monitoring again makes the service quite difficult to use

### Expected Behaviour

Database entries (e.g. user accounts, API keys and monitored APIs) are persistent and reliable.

**Comment by eXodiquas** [comment]
fixed in #6
